//
//  AirportsNearbyInteractor.swift
//  AirportLocator
//
//  Created by Anish Kumar on 06/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AirportsNearbyBusinessLogic
{
  func doSomething(request: AirportsNearby.Something.Request)
}

protocol AirportsNearbyDataStore
{
  //var name: String { get set }
}

class AirportsNearbyInteractor: AirportsNearbyBusinessLogic, AirportsNearbyDataStore
{
  var presenter: AirportsNearbyPresentationLogic?
  var worker: AirportsNearbyWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AirportsNearby.Something.Request)
  {
    worker = AirportsNearbyWorker()
    worker?.doSomeWork()
    
    let response = AirportsNearby.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
