//
//  AirportsNearbyViewController.swift
//  AirportLocator
//
//  Created by Anish Kumar on 06/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation
import MapKit

protocol AirportsNearbyDisplayLogic: class
{
    func displaySomething(viewModel: AirportsNearby.ViewModel)
}

class AirportsNearbyViewController: UIViewController, AirportsNearbyDisplayLogic
{
    var interactor: AirportsNearbyBusinessLogic?
    var router: (NSObjectProtocol & AirportsNearbyRoutingLogic & AirportsNearbyDataPassing)?

    // MARK: Outlets
    
    @IBOutlet weak var mapView: MKMapView!
    
    // MARK: Variables
    let locationManager = CLLocationManager()

    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = AirportsNearbyInteractor()
        let presenter = AirportsNearbyPresenter()
        let router = AirportsNearbyRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        locationManager.requestWhenInUseAuthorization()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        self.setUpMapView()
        super.viewWillAppear(animated)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        showNeabyAirports()
    }
    
    // MARK: Setup map view
    func setUpMapView() {
        mapView.showsBuildings = true
        mapView.showsCompass = true
        mapView.showsUserLocation = true
        mapView.showsScale = true
        
        mapView.camera.pitch = 80.0
        mapView.camera.altitude = 150.0
        mapView.camera.heading = 45.0

        mapView.setUserTrackingMode(.followWithHeading, animated: true)
    }
    
    // MARK: Do something
    
    func showNeabyAirports() {
        let request = AirportsNearby.Request(location: CLLocation(), radius: ALConstants.searchRadius)
        interactor?.showAirportsNearby(request: request)
    }
    
    func displaySomething(viewModel: AirportsNearby.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
