//
//  AirportsNearbyWorker.swift
//  AirportLocator
//
//  Created by Anish Kumar on 06/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation

class AirportsNearbyWorker
{
    /// Gets the airports near a location within the radius
    /// - Parameter request: Request containing the location and search radius
    func getNearbyAirports(request: AirportsNearby.Request) -> AirportsNearby.Response? {
        let responseJson = ALResponseMock.airportsNearbyMockResponse
        do {
            let response = try JSONDecoder().decode(AirportsNearby.Response.self, from: responseJson.data(using: .utf8)!)
            return response
        } catch {
            debugPrint("Failed to convert JSON to response object")
            return nil
        }
    }
}
