//
//  AirportsNearbyInteractor.swift
//  AirportLocator
//
//  Created by Anish Kumar on 06/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation

protocol AirportsNearbyBusinessLogic
{
  func showAirportsNearby(request: AirportsNearby.Request)
}

protocol AirportsNearbyDataStore
{
  //var name: String { get set }
}

class AirportsNearbyInteractor: AirportsNearbyBusinessLogic, AirportsNearbyDataStore
{
  var presenter: AirportsNearbyPresentationLogic?
  var worker: AirportsNearbyWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func showAirportsNearby(request: AirportsNearby.Request) {
    worker = AirportsNearbyWorker()
    
    let response = worker!.getNearbyAirports(request: request)
    presenter?.presentAirportsOnMap(response: response)
  }
}
