//
//  AirportsNearbyPresenter.swift
//  AirportLocator
//
//  Created by Anish Kumar on 06/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation

protocol AirportsNearbyPresentationLogic
{
    func presentAirportsOnMap(response: AirportsNearby.Response?)
}

class AirportsNearbyPresenter: AirportsNearbyPresentationLogic
{
    weak var viewController: AirportsNearbyDisplayLogic?
    
    // MARK: Do something
    
    func presentAirportsOnMap(response: AirportsNearby.Response?) {
        let viewModel = AirportsNearby.ViewModel(findLocation: CLLocationCoordinate2D())

        if let response = response {
            let position = response.search.context.location.position
            viewModel.findLocation = CLLocationCoordinate2D(latitude: position[0], longitude: position[1])
            
            for item in response.results.items {
                let location = CLLocationCoordinate2D(latitude: item.position[0], longitude: item.position[1])
                let distanceInKm = Float(item.distance) / 1000.0
                let distanceString = item.distance >= 1000 ? String(format: "%.2f km", distanceInKm) : String(format: "%d metres", item.distance)
                
                let aiportVM = AirportsNearby.ViewModel.AirportData(id: item.id, title: item.title, location: location, distance: item.distance, distanceString: distanceString)
                viewModel.airports.append(aiportVM)
            }
        }
        
        viewController?.displayAirportAnnotations(viewModel: viewModel)
    }
}
