//
//  AirportsNearbyModels.swift
//  AirportLocator
//
//  Created by Anish Kumar on 06/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation

enum AirportsNearby
{
    
    // MARK: Request
    struct Request {
        let location: CLLocationCoordinate2D
    }
    
    // MARK: - Response
    struct Response: Codable {
        let results: Results
        let search: Search
        
        // MARK: - Results
        struct Results: Codable {
            let items: [Item]
        }
        
        // MARK: - Item
        struct Item: Codable {
            let position: [Double]
            let distance: Int
            let title: String
            let averageRating: Int
            let category: Category
            let icon: String
            let vicinity, type: String
            let href: String
            let id: String
        }
        
        // MARK: - Category
        struct Category: Codable {
            let id, title: String
            let href: String
            let type, system: String
        }
        
        // MARK: - Search
        struct Search: Codable {
            let context: Context
        }
        
        // MARK: - Context
        struct Context: Codable {
            let location: Location
            let type: String
            let href: String
        }
        
        // MARK: - Location
        struct Location: Codable {
            let position: [Double]
            let address: Address
        }
        
        // MARK: - Address
        struct Address: Codable {
            let text, street, postalCode, district: String
            let city, county, stateCode, country: String
            let countryCode: String
        }
    }
    
    // MARK: View Model
    class ViewModel {
        
        var findLocation: CLLocationCoordinate2D
        var airports = [AirportData]()
        
        init(findLocation: CLLocationCoordinate2D) {
            self.findLocation = findLocation
        }
        
        struct AirportData {
            let id: String
            let title: String
            let location: CLLocationCoordinate2D
            let distance: Int
            let distanceString: String?
        }
    }
}
