//
//  AirportsNearbyPresenterTests.swift
//  AirportLocator
//
//  Created by Anish Kumar on 08/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import AirportLocator
import XCTest

class AirportsNearbyPresenterTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: AirportsNearbyPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupAirportsNearbyPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupAirportsNearbyPresenter() {
        sut = AirportsNearbyPresenter()
    }
    
    // MARK: Test doubles
    
    class AirportsNearbyDisplayLogicSpy: AirportsNearbyDisplayLogic
    {
        var displayAirportAnnotationsCalled = false
        
        func displayAirportAnnotations(viewModel: AirportsNearby.ViewModel) {
            displayAirportAnnotationsCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentAirportsOnMap() {
        // Given
        let spy = AirportsNearbyDisplayLogicSpy()
        sut.viewController = spy
        let responseJson = ALResponseMock.airportsNearbyMockResponse
        let response = try? JSONDecoder().decode(AirportsNearby.Response.self, from: responseJson.data(using: .utf8)!)
        
        // When
        sut.presentAirportsOnMap(response: response)
        
        // Then
        XCTAssertTrue(spy.displayAirportAnnotationsCalled, "presentAirportsOnMap(response:) should ask the view controller to display the airport annotations")
    }
}
