//
//  AirportsNearbyInteractorTests.swift
//  AirportLocator
//
//  Created by Anish Kumar on 08/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import AirportLocator
import XCTest
import CoreLocation

class AirportsNearbyInteractorTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: AirportsNearbyInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupAirportsNearbyInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupAirportsNearbyInteractor() {
        sut = AirportsNearbyInteractor()
    }
    
    // MARK: Test doubles
    
    class AirportsNearbyPresentationLogicSpy: AirportsNearbyPresentationLogic
    {
        var presentAirportsOnMapCalled = false
        
        func presentAirportsOnMap(response: AirportsNearby.Response?) {
            presentAirportsOnMapCalled = true
        }
    }
    
    // MARK: Tests
    
    func testShowAirportsNearby() {
        // Given
        let spy = AirportsNearbyPresentationLogicSpy()
        sut.presenter = spy
        let location = CLLocationCoordinate2D(latitude: 10.9796, longitude: 76.9674)
        let request = AirportsNearby.Request(location: location)
        
        // When
        sut.showAirportsNearby(request: request)
        
        // Then
        /* Unable to test due to async call back */
//        XCTAssertTrue(spy.presentAirportsOnMapCalled, "showAirportsNearby(request:) should ask the presenter to format the result")
    }
}
